import tkinter as tk
from tkinter import filedialog, messagebox, scrolledtext
import os  # for filename extraction

# First register map (your original)
REGISTER_MAP_1 = {
    1: 'Code version number',
    2: 'Relay status',
    3: 'Room temperature',
    4: 'Floor temperature',
    5: 'Remote sensor temperature',
    6: 'Window status',
    7: 'Current setting temperature',
    8: 'Thermostat On/Off mode',
    9: 'Current operation mode',
    10: 'Current schedule ',
    11: 'Next schedule ',
    12: 'Daylight saving status',
    13: 'Rate Of Change Information Only',
    14: 'Reserved',
    15: 'Before compensation Board sensor temperature ',
    16: 'After compensation Board sensor temperature',
    17: 'Reserved',
    18: 'Reserved',
    19: 'Reserved',
    20: 'Reserved',
    21: 'Temp Format',
    22: 'Switching Differential',
    23: 'Output Delay',
    24: 'Up/Down Limit ',
    25: 'Sensor Selection ',
    26: 'Floor Limit Temperature ',
    27: 'Optimum Start ',
    28: 'Program Type ',
    29: 'Program Mode ',
    30: '(DST) Daylight Saving ',
    31: 'Communications ID(MODBUS)',
    32: 'Thermostat On/Off mode',
    33: 'Current operation mode',
    34: 'Over right and Hold Set temperature',
    35: 'Advanced Set temperature',
    36: 'Reserved',
    37: 'FrostSet temperature',
    38: 'Holdtime Hour+minute',
    39: 'Awaytime Hour+minute',
    40: 'Awaytime Month+Day',
    41: 'Awaytime Year',
    42: 'KeyLock PassWord',
    43: 'TPI ',
    44: 'TPI minimum On time ',
    45: 'Reserved',
    46: 'Restore the factory Settings',
    47: 'Synchronous RTC Year',
    48: 'Synchronous RTC Month+Day',
    49: 'Synchronous RTC Hour+minute',
    50: 'Synchronous RTC second',
    51: 'Sunday Period1 Hour',
    52: 'Sunday Period1 Minute',
    53: 'Sunday Period1 SetTemp',
    54: 'Reserved',
    55: 'Sunday Period2 Hour',
    56: 'Sunday Period2 Minute',
    57: 'Sunday Period2 SetTemp',
    58: 'Reserved',
    59: 'Sunday Period3 Hour',
    60: 'Sunday Period3 Minute',
    61: 'Sunday Period3 SetTemp',
    62: 'Reserved',
    63: 'Sunday Period4 Hour',
    64: 'Sunday Period4 Minute',
    65: 'Sunday Period4 SetTemp',
    66: 'Reserved',
    67: 'Sunday Period5 Hour',
    68: 'Sunday Period5 Minute',
    69: 'Sunday Period5 SetTemp',
    70: 'Reserved',
    71: 'Sunday Period6 Hour',
    72: 'Sunday Period6 Minute',
    73: 'Sunday Period6 SetTemp',
    74: 'Reserved',
    75: 'Monday Period1 Hour',
    76: 'Monday Period1 Minute',
    77: 'Monday Period1 SetTemp',
    78: 'Reserved',
    79: 'Monday Period2 Hour',
    80: 'Monday Period2 Minute',
    81: 'Monday Period2 SetTemp',
    82: 'Reserved',
    83: 'Monday Period3 Hour',
    84: 'Monday Period3 Minute',
    85: 'Monday Period3 SetTemp',
    86: 'Reserved',
    87: 'Monday Period4 Hour',
    88: 'Monday Period4 Minute',
    89: 'Monday Period4 SetTemp',
    90: 'Reserved',
    91: 'Monday Period5 Hour',
    92: 'Monday Period5 Minute',
    93: 'Monday Period5 SetTemp',
    94: 'Reserved',
    95: 'Monday Period6 Hour',
    96: 'Monday Period6 Minute',
    97: 'Monday Period6 SetTemp',
    98: 'Reserved',
    99: 'Tuesday Period1 Hour',
    100: 'Tuesday Period1 Minute',
    101: 'Tuesday Period1 SetTemp',
    102: 'Reserved',
    103: 'Tuesday Period2 Hour',
    104: 'Tuesday Period2 Minute',
    105: 'Tuesday Period2 SetTemp',
    106: 'Reserved',
    107: 'Tuesday Period3 Hour',
    108: 'Tuesday Period3 Minute',
    109: 'Tuesday Period3 SetTemp',
    110: 'Reserved',
    111: 'Tuesday Period4 Hour',
    112: 'Tuesday Period4 Minute',
    113: 'Tuesday Period4 SetTemp',
    114: 'Reserved',
    115: 'Tuesday Period5 Hour',
    116: 'Tuesday Period5 Minute',
    117: 'Tuesday Period5 SetTemp',
    118: 'Reserved',
    119: 'Tuesday Period6 Hour',
    120: 'Tuesday Period6 Minute',
    121: 'Tuesday Period6 SetTemp',
    122: 'Reserved',
    123: 'Wednesday Period1 Hour',
    124: 'Wednesday Period1 Minute',
    125: 'Wednesday Period1 SetTemp',
    126: 'Reserved',
    127: 'Wednesday Period2 Hour',
    128: 'Wednesday Period2 Minute',
    129: 'Wednesday Period2 SetTemp',
    130: 'Reserved',
    131: 'Wednesday Period3 Hour',
    132: 'Wednesday Period3 Minute',
    133: 'Wednesday Period3 SetTemp',
    134: 'Reserved',
    135: 'Wednesday Period4 Hour',
    136: 'Wednesday Period4 Minute',
    137: 'Wednesday Period4 SetTemp',
    138: 'Reserved',
    139: 'Wednesday Period5 Hour',
    140: 'Wednesday Period5 Minute',
    141: 'Wednesday Period5 SetTemp',
    142: 'Reserved',
    143: 'Wednesday Period6 Hour',
    144: 'Wednesday Period6 Minute',
    145: 'Wednesday Period6 SetTemp',
    146: 'Reserved',
    147: 'Thursday Period1 Hour',
    148: 'Thursday Period1 Minute',
    149: 'Thursday Period1 SetTemp',
    150: 'Reserved',
    151: 'Thursday Period2 Hour',
    152: 'Thursday Period2 Minute',
    153: 'Thursday Period2 SetTemp',
    154: 'Reserved',
    155: 'Thursday Period3 Hour',
    156: 'Thursday Period3 Minute',
    157: 'Thursday Period3 SetTemp',
    158: 'Reserved',
    159: 'Thursday Period4 Hour',
    160: 'Thursday Period4 Minute',
    161: 'Thursday Period4 SetTemp',
    162: 'Reserved',
    163: 'Thursday Period5 Hour',
    164: 'Thursday Period5 Minute',
    165: 'Thursday Period5 SetTemp',
    166: 'Reserved',
    167: 'Thursday Period6 Hour',
    168: 'Thursday Period6 Minute',
    169: 'Thursday Period6 SetTemp',
    170: 'Reserved',
    171: 'Friday Period1 Hour',
    172: 'Friday Period1 Minute',
    173: 'Friday Period1 SetTemp',
    174: 'Reserved',
    175: 'Friday Period2 Hour',
    176: 'Friday Period2 Minute',
    177: 'Friday Period2 SetTemp',
    178: 'Reserved',
    179: 'Friday Period3 Hour',
    180: 'Friday Period3 Minute',
    181: 'Friday Period3 SetTemp',
    182: 'Reserved',
    183: 'Friday Period4 Hour',
    184: 'Friday Period4 Minute',
    185: 'Friday Period4 SetTemp',
    186: 'Reserved',
    187: 'Friday Period5 Hour',
    188: 'Friday Period5 Minute',
    189: 'Friday Period5 SetTemp',
    190: 'Reserved',
    191: 'Friday Period6 Hour',
    192: 'Friday Period6 Minute',
    193: 'Friday Period6 SetTemp',
    194: 'Reserved',
    195: 'Saturday Period1 Hour',
    196: 'Saturday Period1 Minute',
    197: 'Saturday Period1 SetTemp',
    198: 'Reserved',
    199: 'Saturday Period2 Hour',
    200: 'Saturday Period2 Minute',
    201: 'Saturday Period2 SetTemp',
    202: 'Reserved',
    203: 'Saturday Period3 Hour',
    204: 'Saturday Period3 Minute',
    205: 'Saturday Period3 SetTemp',
    206: 'Reserved',
    207: 'Saturday Period4 Hour',
    208: 'Saturday Period4 Minute',
    209: 'Saturday Period4 SetTemp',
    210: 'Reserved',
    211: 'Saturday Period5 Hour',
    212: 'Saturday Period5 Minute',
    213: 'Saturday Period5 SetTemp',
    214: 'Reserved',
    215: 'Saturday Period6 Hour',
    216: 'Saturday Period6 Minute',
    217: 'Saturday Period6 SetTemp',
    218: 'Reserved'
}
for i in range(1, 219):
    REGISTER_MAP_1.setdefault(i, f"Register {i}")

# Second register map example (customize as needed)
REGISTER_MAP_2 = {
    1: 'Code version number',
    2: 'Relay status',
    3: 'Thermostat On/Off mode',
    4: 'Current schedule',
    5: 'Next schedule',
    6: 'Daylight saving status',
    7: 'Reserved',
    8: 'Reserved',
    9: 'Current operation mode',
    10: 'Reserved',
    11: 'Reserved',
    12: 'Reserved',
    13: 'Reserved',
    14: 'Reserved',
    15: 'Reserved',
    16: 'Reserved',
    17: 'Reserved',
    18: 'Reserved',
    19: 'Reserved',
    20: 'Reserved',
    21: 'Reserved',
    22: 'Reserved',
    23: 'Reserved',
    24: 'Reserved',
    25: 'Reserved',
    26: 'Reserved',
    27: 'Reserved',
    28: 'Reserved',
    29: 'Program Mode',
    30: '(DST) Daylight Saving',
    31: 'Communications ID(MODBUS)',
    32: 'Thermostat On/Off mode',
    33: 'Current operation mode',
    34: 'Timer Out force',
    35: 'Reserved',
    36: 'Reserved',
    37: 'Reserved',
    38: 'Holdtime Hour+minute',
    39: 'Awaytime Hour+minute',
    40: 'Awaytime Month+Day',
    41: 'Awaytime Year',
    42: 'Reserved',
    43: 'Reserved',
    44: 'Reserved',
    45: 'Reserved',
    46: 'Restore the factory Settings',
    47: 'Synchronous RTC Year',
    48: 'Synchronous RTC Month+Day',
    49: 'Synchronous RTC Hour+minute',
    50: 'Synchronous RTC second',
    51: 'Sunday Period1 On Hour',
    52: 'Sunday Period1 On MIN',
    53: 'Sunday Period1 Off Hour',
    54: 'Sunday Period1 Off MIN',
    55: 'Sunday Period2 On Hour',
    56: 'Sunday Period2 On MIN',
    57: 'Sunday Period2 Off Hour',
    58: 'Sunday Period2 Off MIN',
    59: 'Sunday Period3 On Hour',
    60: 'Sunday Period3 On MIN',
    61: 'Sunday Period3 Off Hour',
    62: 'Sunday Period3 Off MIN',
    63: 'Sunday Period4 On Hour',
    64: 'Sunday Period4 On MIN',
    65: 'Sunday Period4 Off Hour',
    66: 'Sunday Period4 Off MIN',
    67: 'Monday Period1 On Hour',
    68: 'Monday Period1 On MIN',
    69: 'Monday Period1 Off Hour',
    70: 'Monday Period1 Off MIN',
    71: 'Monday Period2 On Hour',
    72: 'Monday Period2 On MIN',
    73: 'Monday Period2 Off Hour',
    74: 'Monday Period2 Off MIN',
    75: 'Monday Period3 On Hour',
    76: 'Monday Period3 On MIN',
    77: 'Monday Period3 Off Hour',
    78: 'Monday Period3 Off MIN',
    79: 'Monday Period4 On Hour',
    80: 'Monday Period4 On MIN',
    81: 'Monday Period4 Off Hour',
    82: 'Monday Period4 Off MIN',
    83: 'Tuesday Period1 On Hour',
    84: 'Tuesday Period1 On MIN',
    85: 'Tuesday Period1 Off Hour',
    86: 'Tuesday Period1 Off MIN',
    87: 'Tuesday Period2 On Hour',
    88: 'Tuesday Period2 On MIN',
    89: 'Tuesday Period2 Off Hour',
    90: 'Tuesday Period2 Off MIN',
    91: 'Tuesday Period3 On Hour',
    92: 'Tuesday Period3 On MIN',
    93: 'Tuesday Period3 Off Hour',
    94: 'Tuesday Period3 Off MIN',
    95: 'Tuesday Period4 On Hour',
    96: 'Tuesday Period4 On MIN',
    97: 'Tuesday Period4 Off Hour',
    98: 'Tuesday Period4 Off MIN',
    99: 'Wednesday Period1 On Hour',
    100: 'Wednesday Period1 On MIN',
    101: 'Wednesday Period1 Off Hour',
    102: 'Wednesday Period1 Off MIN',
    103: 'Wednesday Period2 On Hour',
    104: 'Wednesday Period2 On MIN',
    105: 'Wednesday Period2 Off Hour',
    106: 'Wednesday Period2 Off MIN',
    107: 'Wednesday Period3 On Hour',
    108: 'Wednesday Period3 On MIN',
    109: 'Wednesday Period3 Off Hour',
    110: 'Wednesday Period3 Off MIN',
    111: 'Wednesday Period4 On Hour',
    112: 'Wednesday Period4 On MIN',
    113: 'Wednesday Period4 Off Hour',
    114: 'Wednesday Period4 Off MIN',
    115: 'Thursday Period1 On Hour',
    116: 'Thursday Period1 On MIN',
    117: 'Thursday Period1 Off Hour',
    118: 'Thursday Period1 Off MIN',
    119: 'Thursday Period2 On Hour',
    120: 'Thursday Period2 On MIN',
    121: 'Thursday Period2 Off Hour',
    122: 'Thursday Period2 Off MIN',
    123: 'Thursday Period3 On Hour',
    124: 'Thursday Period3 On MIN',
    125: 'Thursday Period3 Off Hour',
    126: 'Thursday Period3 Off MIN',
    127: 'Thursday Period4 On Hour',
    128: 'Thursday Period4 On MIN',
    129: 'Thursday Period4 Off Hour',
    130: 'Thursday Period4 Off MIN',
    131: 'Friday Period1 On Hour',
    132: 'Friday Period1 On MIN',
    133: 'Friday Period1 Off Hour',
    134: 'Friday Period1 Off MIN',
    135: 'Friday Period2 On Hour',
    136: 'Friday Period2 On MIN',
    137: 'Friday Period2 Off Hour',
    138: 'Friday Period2 Off MIN',
    139: 'Friday Period3 On Hour',
    140: 'Friday Period3 On MIN',
    141: 'Friday Period3 Off Hour',
    142: 'Friday Period3 Off MIN',
    143: 'Friday Period4 On Hour',
    144: 'Friday Period4 On MIN',
    145: 'Friday Period4 Off Hour',
    146: 'Friday Period4 Off MIN',
    147: 'Saturday Period1 On Hour',
    148: 'Saturday Period1 On MIN',
    149: 'Saturday Period1 Off Hour',
    150: 'Saturday Period1 Off MIN',
    151: 'Saturday Period2 On Hour',
    152: 'Saturday Period2 On MIN',
    153: 'Saturday Period2 Off Hour',
    154: 'Saturday Period2 Off MIN',
    155: 'Saturday Period3 On Hour',
    156: 'Saturday Period3 On MIN',
    157: 'Saturday Period3 Off Hour',
    158: 'Saturday Period3 Off MIN',
    159: 'Saturday Period4 On Hour',
    160: 'Saturday Period4 On MIN',
    161: 'Saturday Period4 Off Hour',
    162: 'Saturday Period4 Off MIN'
}
for i in range(1, 219):
    REGISTER_MAP_2.setdefault(i, f"Register {i}")

# Dictionary of maps for easy access
REGISTER_MAPS = {
    "Thermostat": REGISTER_MAP_1,
    "Timer": REGISTER_MAP_2,
}

def decode_registers(values, register_map):
    decoded = []
    for i, val in enumerate(values, start=1):
        label = register_map.get(i, f"Register {i}")
        decoded.append(f"{i:03}: {label} = {val}")
    return "\n".join(decoded)

def load_file():
    filepath = filedialog.askopenfilename(filetypes=[("Text Files", "*.txt")])
    if not filepath:
        return

    try:
        with open(filepath, "r") as f:
            content = f.read()
            raw_values = [v.strip() for v in content.strip().split(",") if v.strip()]
            values = list(map(int, raw_values))

        selected_map_name = map_var.get()
        selected_map = REGISTER_MAPS[selected_map_name]

        result = decode_registers(values, selected_map)
        output_area.delete("1.0", tk.END)
        output_area.insert(tk.END, result)

        filename = os.path.basename(filepath)
        file_label.config(text=f"Loaded file: {filename}")

    except Exception as e:
        messagebox.showerror("Error", f"Failed to load file:\n{e}")
        file_label.config(text="")  # Clear label on error

# UI setup
root = tk.Tk()
root.title("Modbus Register Decoder")

# Make the root window expandable
root.rowconfigure(0, weight=1)
root.columnconfigure(0, weight=1)

frame = tk.Frame(root, padx=10, pady=10)
frame.grid(sticky="nsew")  # use grid for better control
frame.rowconfigure(4, weight=1)  # output_area is row 4, make it expand vertically
frame.columnconfigure(0, weight=1)

# Dropdown to select map
map_var = tk.StringVar(value="Thermostat")
map_menu = tk.OptionMenu(frame, map_var, *REGISTER_MAPS.keys())
map_menu.grid(row=0, column=0, sticky="ew", pady=5)

load_btn = tk.Button(frame, text="Load Register File", command=load_file)
load_btn.grid(row=1, column=0, sticky="ew", pady=5)

file_label = tk.Label(frame, text="No file loaded")
file_label.grid(row=2, column=0, sticky="w", pady=5)

# Spacer row to separate label and output area (optional)
frame.rowconfigure(3, minsize=5)

output_area = scrolledtext.ScrolledText(frame, wrap=tk.WORD)
output_area.grid(row=4, column=0, sticky="nsew", pady=5)

root.mainloop()
